# Generated by Django 5.2.5 on 2025-12-26 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('pending', 'Pending Trade'), ('sold', 'Sold')], default='available', help_text='Current status of the product', max_length=20),
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Name of the product to purchase', max_length=255)),
                ('description', models.TextField(help_text='Description of the product to purchase')),
                ('target_price', models.DecimalField(decimal_places=2, help_text='Target price for the product', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date the purchase request was created')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
